app:
  name: anuglar2-spring-jwt

jwt:
  header: Authorization
  expires_in: 36000 # 10 minutes
  secret: queenvictoria
  cookie: AUTH-TOKEN

logging:
  level:
    org.springframework.web: INFO
    org.hibernate: INFO
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
    com.bfwg: DEBUG
