jrocks:
  name: jrocks
  version: ${project.version}
  configFilename: .jrocks
  pluginDirectory: ${JROCKS_HOME}/plugins

spring:
  banner:
    location: classpath:/banner.txt
    charset: UTF-8

logging:
  level:
    ROOT: ERROR

